#!/usr/bin/env bash

# Logging to the prompt
e_info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

e_user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

e_success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

e_fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

login_to_Mac_App_Store () {
#	Attempt at workaround for High Sierra error that prevents logging into Mac App Store
#		See Mike Ratcliffe, https://github.com/mas-cli/mas/issues/107#issuecomment-335514316

# Test if signed in. If not, launch MAS and sign in.

until (mas account > /dev/null); # If signed in, drop to outer "done"
do
#	If here, not logged in

	echo -e "You are not yet logged into the Mac App Store."
	echo -e "I will launch the Mac App Store now."
	echo -e "\nPlease log in to the Mac App Store..."
	open -a "/Applications/App Store.app"

#	until loop waits patiently until scriptrunner signs into Mac App Store
	until (mas account > /dev/null);
	do
		sleep 3
    	echo -e "… zzz …."
  	done	
done
echo -e "You are signed into the Mac App Store."
signed_in_user=$(mas account)
echo -e "MAS user name: $signed_in_user"
}


# Test whether a command exists
# $1 - cmd to test
type_exists() {
    if [ $(type -P $1) ]; then
      return 0
    fi
    return 1
}