#!/usr/bin/env bash

# Logging to the prompt
e_info () {
  printf "  [ \033[00;34m..\033[0m ] $1\n"
}

e_user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

e_success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

e_fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}


# Test whether a command exists
# $1 - cmd to test
type_exists() {
    if [ $(type -P $1) ]; then
      return 0
    fi
    return 1
}