#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"

source ${DOTFILES_ROOT}/lib/utils

set -e

echo ''
echo 'Bootstrapping local environment'
echo ''

# Before relying on Homebrew, check that packages can be compiled
if ! type_exists 'gcc'; then
    e_error "The XCode Command Line Tools must be installed first."
    e_info "  Run in a terminal gcc and follow instructions for installation"
    e_info "  Then run: bash ~/.dotfiles/script/bootstrap"
    exit 1
fi

# Check for Homebrew
if ! type_exists 'brew'; then
    e_info "Installing Homebrew..."
    ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"
fi

# Check if git comes from Homebrew and install if needed
if brew list | grep --quiet git; then
  e_info "Homebrew version of git already installed!"
else
  e_info "Updating Homebrew..."
  brew update
  e_info "Installing Git..."
  brew install git
  e_user "New git version will be used after you close the terminal :("
fi

echo ''
echo 'All installed!'
