#!/usr/bin/env bash
#
# bootstrap installs things.

DOTFILES_ROOT="`pwd`"

source ./lib/utils

set -e

echo ''
echo 'Bootstrapping local environment'
echo ''

# Before relying on Homebrew, check that packages can be compiled
if ! type_exists 'gcc'; then
    e_error "The XCode Command Line Tools must be installed first."
    printf "  Run in a terminal gcc and follow instructions for installation\n"
    printf "  Then run: bash ~/.dotfiles/script/bootstrap\n"
    exit 1
fi

echo ''
echo '  All installed!'
