return {
  -- AIDEV-NOTE: Set tokyonight-storm as the default LazyVim colorscheme
  -- lazy=false and priority ensure it loads before other plugins
  -- on_highlights clears Normal bg for terminal transparency
  {
    "folke/tokyonight.nvim",
    lazy = false,
    priority = 1000,
    opts = {
      style = "storm",
      transparent = true,
      styles = {
        sidebars = "transparent",
        floats = "transparent",
      },
      on_highlights = function(hl, c)
        hl.Normal = { fg = c.fg, bg = "NONE" }
        hl.NormalFloat = { fg = c.fg, bg = "NONE" }
      end,
    },
  },
  -- AIDEV-NOTE: dms colorscheme needs AvengeMedia/base46; theme files
  -- (~/.config/nvim/colors/dms.lua) are generated by `dms matugen generate`
  {
    "AvengeMedia/base46",
    lazy = true,
    opts = {},
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "dms",
    },
  },
}
