#!/bin/env bash

USER=geert

function run() {
  DBUS=unix:path=/run/user/$(id -u $USER)/bus
  cd /home/$USER || exit
  sudo -u $USER DBUS_SESSION_BUS_ADDRESS="$DBUS" /usr/bin/systemd-run --user --property=TimeoutStopSec=1 --property=KillMode=mixed "$@"
}

# if this runs as root, run it as user
if [ "$EUID" -eq 0 ]; then
  run $0 "$@"
  exit 0
fi

# true when on battery
if [ "$1" = "true" ]; then
  brightnessctl -d intel_backlight -s set 40% # save brightness
  xrandr -r 60
  # tuned-adm profile laptop-battery-powersave
  # powerprofilesctl set power-saver
  # hyprctl keyword decoration:drop_shadow false
  # hyprctl keyword decoration:blur:enabled false
fi

if [ "$1" = "false" ]; then
  brightnessctl -d intel_backlight -r # restore brightness
  xrandr -r 120
  # powerprofilesctl set balanced
  # tuned-adm profile laptop-ac-powersave
  #  hyprctl keyword decoration:drop_shadow true
  #  hyprctl keyword decoration:blur:enabled true
fi

# reload waybar
# pkill waybar
# waybar
